# -*- coding: utf-8 -*-
"""Lab_1_Hello_World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otxJtJTaU2lNQpC0ib7lMA8F-f2xGCt_
"""



import tensorflow as tf
import numpy as np

#Build a Simple Sequential Model
model = tf.keras.Sequential([

    # Define the Input Shape
    tf.keras.Input(shape=(1,)),

    # Add a Dense Layer
    tf.keras.layers.Dense(units=1)
])

# Compile the Model
model.compile(optimizer='sgd', loss='mean_squared_error')

# Declare the Model Inputs for Training
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

# Train the Model
model.fit(xs, ys, epochs=500)

# Make a Prediction
print(f"model predicted: {model.predict(np.array([10.0]), verbose=0).item():.5f}")